services:
  db:
    image: postgres:15-alpine
    container_name: sentinel_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: sentinel_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sentinel.com
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

  ingestion:
    build: ./services/ingestion
    container_name: sentinel_ingestor
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      DROP_MARGIN: ${DROP_MARGIN}
      WATCH_LIST: "bitcoin,ethereum,solana"
    depends_on:
      - db

  api:
    build: ./services/api
    container_name: sentinel_api
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - db

  sentiment:
    build: ./services/sentiment
    container_name: sentinel_ai
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
    depends_on:
      - db

  dashboard:
    build: ./services/dashboard
    container_name: sentinel_dashboard
    restart: always
    environment:
      API_URL: ${API_URL}
      TG_BOT_USERNAME: ${TG_BOT_USERNAME}
    ports:
      - "8501:8501"
    depends_on:
      - api

  portainer:
    image: portainer/portainer-ce:latest
    container_name: sentinel_portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    ports:
      - "9000:9000"

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: sentinel_tunnel
    restart: always
    command: tunnel --url http://sentinel_dashboard:8501
    depends_on:
      - dashboard

volumes:
  postgres_data:
  portainer_data:
